Add preference to hide the enclosure view
ViennaRSS/vienna-rss pull request #1576
Opened 2022-06-17 11:23 UTC by Eitot

This was suggested here: https://forums.cocoaforge.com/viewtopic.php?f=18&t=27230.

2022-09-26 00:40 UTC, barijaona approved these changes

2022-09-26 06:26 UTC, barijaona requested changes

2022-09-26 06:26 UTC, barijaona commented on Vienna/Sources/Main window/ArticleListView.m
> +        if (showEnclosureBar.boolValue) {
Cf. -refreshArticlePane : showing the enclosure view should be done if : 
- just one article is displayed
- the article has an enclosure

2022-09-26 08:15 UTC, barijaona requested changes
For consistency, showing the enclosure view should only be done if :
- just one article is displayed
- the article has an enclosure

2022-09-26 08:15 UTC, barijaona commented on Vienna/Sources/Main window/ArticleListView.m
> +            [self showEnclosureView];
```suggestion
            [self refreshArticlePane];
```

2022-09-29 05:52 UTC, barijaona approved these changes

2022-09-29 05:53 UTC, merged

2022-09-29 06:02 UTC, barijaona commented
> I did not even know that you can view multiple articles at once.

Yeah, it's one of the features I like most in Vienna, for quickly scrolling through folders containing photos thumbnails…

Neither NetNewsWire or Reeder have this.

2022-11-09 15:50 UTC, barijaona commented
@Eitot : the new menu item "Hide Status Bar" has not yet been exported to Crowding for localization…
Is there any reason ?

2022-11-10 04:47 UTC, barijaona commented
I understand. But it will leave final versions of 3.8.x looking half finished 😀. In the future, we should coordinate a little more regarding merging of features branches.

2022-11-10 04:57 UTC, josh64x2 commented
@barijaona co-ordination is definitely welcome, do you have any method in mind?

2022-11-10 10:37 UTC, barijaona commented
@Eitot thanks !
@josh64x2 how about a "requests translation" label for PRs ?