Stabilize width of article list
ViennaRSS/vienna-rss pull request #1597
Opened 2022-07-17 06:24 UTC by barijaona

With the "Load Full HTML" setting enabled, changes of article list width
were sometimes seen.

We modify holding priorities for subviews of SplitView2
Need feedback to make sure this change is good enough for any website.

2022-07-17 06:34 UTC, barijaona commented
Seems to work better with old browser than with new browser.

Any ideas ?

2022-07-21 06:00 UTC, josh64x2 requested changes
I haven't had a chance to debug yet, but now the vertical layout is broken and I'm unable to resize it:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/799345/180140409-a526a80a-8da1-42b7-a05a-658a127d169f.png">

2022-07-21 06:12 UTC, josh64x2 commented
OK I was also unable to fix the vertical layout in `master` until I turned off the new browser preview, so it wasn't caused by this PR.

I do have reliable way of reproducing a broken Vertical layout though so let me try and debug this over the next couple of days!

2022-07-23 06:12 UTC, barijaona commented
It appears to me that, for some unknown reason, some WkWebView will get higher content compression resistance priority / content hugging priority than legacy WebView

2022-07-23 06:14 UTC, barijaona commented
> I haven't had a chance to debug yet, but now the vertical layout is broken and I'm unable to resize it:

And it's worst on 10.12… 😟

2022-08-11 19:36 UTC, barijaona commented
New version submitted.
I have tried many approaches, but could not find anything simpler that covers all the combinations I tested.
Tested with vertical layout and "Load full HTML" enabled on feeds https://www.lemonde.fr/rss/une.xml and http://www.confidential-renault.fr/?rss=RSS

2022-08-11 19:40 UTC, barijaona commented
> I do have reliable way of reproducing a broken Vertical layout though so let me try and debug this over the next couple of days!
Do you reproduce the problem with my latest version ?

2022-08-11 21:39 UTC, barijaona commented
I am currently unable to test on older versions of macOS. If anyone can provide feedback, it will be welcomed.

2022-08-14 08:26 UTC, josh64x2 commented
I will test this tomorrow and let you know how it goes!

2022-08-15 01:25 UTC, josh64x2 approved these changes
Looks good to me... either that or I've forgotten how to reproduce the issue 😆

2022-08-16 11:25 UTC, merged