Add initial JSON Feed support
ViennaRSS/vienna-rss pull request #1649
Opened 2023-01-01 15:41 UTC by Eitot

This was requested here: #889 

This is a basic implementation based on the [JSON Feed spec](https://www.jsonfeed.org/version/1.1/), using Swift's Codable protocols and JSONDecoder. I have not added any code to sanitise the data yet (e.g. removing whitespace, parsing malformed HTML, etc). I have also not added JSONFeed support to the "feed discoverer", so for now those feeds can only be added manually.

I have made some changes to the code structure of the RichXMLParser as well, notably:
- Added model classes for Atom and RSS feeds and moved the relevant initialisation code out of RichXMLParser (I have not touched the code itself much, it should work just like before)
- Added Feed and FeedItem protocols for properties that are shared by all the feed types, which all feed types must adopt
- Renamed some of the variable names of feeds and feed items to clarify their purpose. (It took me a while before I realised that the "description" data field of RSS is the content/body of the feed item, not a description.)

What can be further improved:
- Remove some responsibilities from RefreshManager. RefreshManager is currently responsible for fetching data and for initialising Folder/Article objects. It also transforms the parsed XML/JSON data before it initialises the Folder/Article objects, which makes it needlessly difficult to see how Vienna handles missing or "malformed" data fields.
- Improve local caching of JSON files (RefreshManager currently creates only files with .xml extension)
- Include a JSON Feed validator (if one exists) in the Get Info panel

Also: Atom and JSON Feed have support for multiple attachments, which Vienna currently does not use. This should be revisited. Unfortunately, I think this is impossible without changing the SQLite schema. It may also be worthwhile to resolve #1472 at the same time (e.g. by recording the saved file name in the database).

2023-01-13 01:49 UTC, josh64x2 commented on Vienna/Sources/Parsing/XMLFeed.m
> +    self.mediaPrefix = [element resolvePrefixForNamespaceURI:@"http://search.yahoo.com/mrss/"];
Just noticed this link is probably broken now hah

2023-01-13 01:50 UTC, josh64x2 commented on Vienna/Sources/Parsing/XMLFeed.m
> +    self.encPrefix = [element resolvePrefixForNamespaceURI:@"http://purl.oclc.org/net/rss_2.0/enc#"];
this one is dead too - I'll open a new PR with fixes for this. I only mentioned it here because I noticed it.

2023-04-01 20:53 UTC, barijaona requested changes
> Atom and JSON Feed have support for multiple attachments, which Vienna currently does not use. This should be revisited.

Before that, the JSON parser should have a smarter handling of articles without attachments. 
Currently, the article view (with default style) displays "Enclosure:" for all articles, even when they don't have any attachment.

2023-04-02 16:59 UTC, barijaona commented
> Currently, the article view (with default style) displays "Enclosure:" for all articles, even when they don't have any attachment.

OK, in fact, there is a bug in ArticleConverter which does not handle correctly nil data in conditional templates

2023-04-02 17:43 UTC, barijaona approved these changes

2023-04-02 17:45 UTC, merged